version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: familyfinance
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
