version: '3'

services:
  db:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=familyfinance
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
