spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://aws.connect.psdb.cloud/familyfinance-db?sslMode=VERIFY_IDENTITY
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    changeLog: classpath:/db/changelog/liquibase-changelog.xml