spring:
  datasource:
    url: jdbc:postgresql://familyfinance-server.postgres.database.azure.com:5432/postgres?user=${DB_USER}&password=${DB_PASSWORD}&sslmode=require
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: family_finance
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog.xml