spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/familyfinance
    hikari:
      schema: familyfinance
  liquibase:
    changeLog: classpath:/db/changelog/liquibase-changelog.xml