spring:
  datasource:
    url: jdbc:postgresql://familyfinance-server.postgres.database.azure.com:5432/postgres?user=${{ secrets.DB_USER }}&password=${{ secrets.DB_PASSWORD }}&sslmode=require
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: family_finance
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog.xml
